version: '3.8'
services:
  server:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: |
      npm run start:dev
      prisma migrate dev
    ports:
      - "3999:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'Workflow'
      MYSQL_DATABASE: 'Workflow'
      MYSQL_USER: 'Workflow'
      MYSQL_PASSWORD: 'Workflow'
